services:
   nextjs:
      build:
         context: .
         dockerfile: ${DOCKER_FILE}
      container_name: nextjs-app
      ports:
         - "3001:3001"
      networks:
         - app_network
      volumes:
         - .:/app
         - /app/node_modules
         - /app/.next
      restart: always

   nginx:
      image: nginx:latest
      container_name: nginx-proxy

      ports:
         - "80:80"
         - "443:443"
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
         - ./certbot/conf:/etc/letsencrypt # config for certbot certificates
         - ./certbot/www:/var/www/certbot # for certbot challenge
      depends_on:
         - nextjs
      networks:
         - app_network
      deploy:
         replicas: ${NGINX_ENABLED:-1}
      restart: always
   certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
         - ./certbot/conf:/etc/letsencrypt
         - ./certbot/www:/var/www/certbot
      depends_on:
         - nginx
      networks:
         - app_network

networks:
   app_network:
      driver: bridge
