services:
   nextjs:
      build: .
      container_name: edservicetx
      restart: always
      ports:
         - "3000:3000"
      networks:
         - nextjs-app
   nginx:
      image: nginx:latest
      container_name: edservicetx_nginx
      restart: always
      ports:
         - "80:80"
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
      depends_on:
         - nextjs
      networks:
         - nextjs-app
   certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
         - ./certbot/conf:/etc/letsencrypt
         - ./certbot/www:/var/www/certbot
      depends_on:
         - nginx
      networks:
         - nextjs-app
networks:
   nextjs-app:
      driver: bridge
