services:
   nextjs:
      build: .
      container_name: nextjs-app
      ports:
         - "3000:3000"
      networks:
         - app_network
      restart: always
   nginx:
      image: nginx:latest
      container_name: nginx-proxy

      ports:
         - "80:80"
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
         - ./certbot/conf:/etc/letsencrypt # config for certbot certificates
         - ./certbot/www:/var/www/certbot # for certbot challenge
      depends_on:
         - nextjs
      networks:
         - app_network
      restart: always
   certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
         - ./certbot/conf:/etc/letsencrypt
         - ./certbot/www:/var/www/certbot
      depends_on:
         - nginx
      networks:
         - app_network
networks:
   app_network:
      driver: bridge
